package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/mattn/go-isatty"
	"github.com/roygabriel/crux/internal/examples"
	"github.com/roygabriel/crux/internal/scaffold"
	"github.com/roygabriel/crux/internal/wizard"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var (
	forceFlag       bool
	exampleFlag     string
	noInteractive   bool
)

// knownExamples maps example names to their embedded FS loader functions.
var knownExamples = map[string]func() (fs.FS, error){
	"httpapi": examples.HTTPAPIFS,
}

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize project directory structure",
	Long:  "Creates .crux/ state directory, copies default config, creates docs/phases/ and work-notes/ directories, copies templates, and updates .gitignore.",
	RunE:  runInit,
}

func init() {
	initCmd.Flags().BoolVar(&forceFlag, "force", false, "Overwrite template files (never overwrites config)")
	initCmd.Flags().StringVar(&exampleFlag, "example", "", "Seed project with a named example (e.g. httpapi)")
	initCmd.Flags().BoolVarP(&noInteractive, "no-interactive", "y", false, "Skip interactive wizard, use defaults")
}

func runInit(cmd *cobra.Command, args []string) error {
	// Determine whether to run the interactive wizard.
	interactive := !noInteractive && exampleFlag == "" && isTerminal()

	dirs := []string{
		".crux",
		"docs/phases",
		"work-notes",
	}

	for _, dir := range dirs {
		created, err := ensureDir(dir)
		if err != nil {
			return err
		}
		if created {
			fmt.Printf("\u2713 Created %s/\n", dir)
		} else {
			fmt.Printf("\u2022 Skipped %s/ (exists)\n", dir)
		}
	}

	cfgPath := filepath.Join(".crux", "config.yaml")

	if interactive {
		return runWizardInit(cfgPath)
	}

	return runDefaultInit(cfgPath)
}

// runWizardInit runs the interactive TUI wizard, writes the resulting
// config, then proceeds with templates, gitignore, and optional example seeding.
func runWizardInit(cfgPath string) error {
	result, err := wizard.Run()
	if err != nil {
		return fmt.Errorf("wizard: %w", err)
	}

	// Marshal and write the wizard-generated config.
	data, err := yaml.Marshal(result.Config)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	header := "# Generated by crux init\n"
	if err := os.WriteFile(cfgPath, []byte(header+string(data)), 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	fmt.Printf("\u2713 Created %s\n", cfgPath)

	// Copy templates from embedded FS.
	if err := writeTemplates(); err != nil {
		return err
	}

	// Ensure .gitignore entries.
	if err := updateGitignore(); err != nil {
		return err
	}

	// Seed example if requested by the wizard.
	if result.SeedExample {
		return seedExample(cfgPath, "httpapi")
	}

	return nil
}

// runDefaultInit uses the embedded default config and optional --example flag.
func runDefaultInit(cfgPath string) error {
	// Write default config from embedded resource (never overwritten, even with --force).
	if _, err := os.Stat(cfgPath); os.IsNotExist(err) {
		if err := os.WriteFile(cfgPath, scaffold.DefaultConfig(), 0o644); err != nil {
			return fmt.Errorf("write config: %w", err)
		}
		fmt.Printf("\u2713 Created %s\n", cfgPath)
	} else {
		fmt.Printf("\u2022 Skipped %s (exists)\n", cfgPath)
	}

	// Copy templates from embedded FS.
	if err := writeTemplates(); err != nil {
		return err
	}

	// Ensure .gitignore entries.
	if err := updateGitignore(); err != nil {
		return err
	}

	// Seed with example project if requested.
	if exampleFlag != "" {
		return seedExample(cfgPath, exampleFlag)
	}

	return nil
}

// writeTemplates copies embedded template files to the templates/ directory.
func writeTemplates() error {
	tplFS, err := scaffold.TemplatesFS()
	if err != nil {
		return fmt.Errorf("load templates: %w", err)
	}
	created, skipped, err := writeEmbeddedFS(tplFS, "templates", forceFlag)
	if err != nil {
		return fmt.Errorf("copy templates: %w", err)
	}
	for _, name := range created {
		fmt.Printf("\u2713 Created templates/%s\n", name)
	}
	for _, name := range skipped {
		fmt.Printf("\u2022 Skipped templates/%s (exists)\n", name)
	}
	return nil
}

// updateGitignore ensures required entries are present in .gitignore.
func updateGitignore() error {
	entries := []string{
		".crux/memory.db",
		".crux/vectors/",
		".crux/audit.log",
		".crux/secrets.env",
	}
	added, err := ensureGitignoreEntries(".gitignore", entries)
	if err != nil {
		return fmt.Errorf("update gitignore: %w", err)
	}
	if added > 0 {
		fmt.Printf("\u2713 Updated .gitignore (added %d entries)\n", added)
	} else {
		fmt.Printf("\u2022 .gitignore already up to date\n")
	}
	return nil
}

// seedExample loads a named example and writes its files.
func seedExample(cfgPath, name string) error {
	exFS, err := loadExample(name)
	if err != nil {
		return err
	}

	// Extract config.yaml from example and write to .crux/config.yaml.
	exCfgData, readErr := fs.ReadFile(exFS, "config.yaml")
	if readErr == nil {
		if err := os.WriteFile(cfgPath, exCfgData, 0o644); err != nil {
			return fmt.Errorf("write example config: %w", err)
		}
		fmt.Printf("\u2713 Updated %s (from example)\n", cfgPath)
	}

	// Write remaining example files, skipping config.yaml (already handled).
	exCreated, exSkipped, err := writeEmbeddedFSSkip(exFS, ".", forceFlag, "config.yaml")
	if err != nil {
		return fmt.Errorf("write example: %w", err)
	}
	for _, name := range exCreated {
		fmt.Printf("\u2713 Created %s\n", name)
	}
	for _, name := range exSkipped {
		fmt.Printf("\u2022 Skipped %s (exists)\n", name)
	}

	return nil
}

// isTerminal returns true if stdin is connected to a terminal.
func isTerminal() bool {
	return isatty.IsTerminal(os.Stdin.Fd()) || isatty.IsCygwinTerminal(os.Stdin.Fd())
}

// loadExample resolves a named example to its embedded FS. It returns
// an error listing available examples if the name is unknown.
func loadExample(name string) (fs.FS, error) {
	loader, ok := knownExamples[name]
	if !ok {
		available := make([]string, 0, len(knownExamples))
		for k := range knownExamples {
			available = append(available, k)
		}
		return nil, fmt.Errorf("unknown example %q; available: %s", name, strings.Join(available, ", "))
	}
	return loader()
}

// ensureDir creates a directory if it doesn't exist.
// Returns true if the directory was created, false if it already existed.
func ensureDir(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return false, nil
	}
	if !os.IsNotExist(err) {
		return false, fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.MkdirAll(path, 0o755); err != nil {
		return false, fmt.Errorf("create directory %s: %w", path, err)
	}
	return true, nil
}

// ensureGitignoreEntries appends missing entries to a .gitignore file.
// Returns the number of entries added.
func ensureGitignoreEntries(path string, entries []string) (int, error) {
	var existing string
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return 0, fmt.Errorf("read gitignore: %w", err)
	}
	if err == nil {
		existing = string(data)
	}

	var missing []string
	for _, entry := range entries {
		if !gitignoreContains(existing, entry) {
			missing = append(missing, entry)
		}
	}

	if len(missing) == 0 {
		return 0, nil
	}

	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return 0, fmt.Errorf("open gitignore: %w", err)
	}
	defer f.Close()

	if len(existing) > 0 && !strings.HasSuffix(existing, "\n") {
		if _, err := f.WriteString("\n"); err != nil {
			return 0, fmt.Errorf("write gitignore: %w", err)
		}
	}

	for _, entry := range missing {
		if _, err := f.WriteString(entry + "\n"); err != nil {
			return 0, fmt.Errorf("write gitignore: %w", err)
		}
	}

	return len(missing), nil
}

// gitignoreContains checks whether a .gitignore content string contains the given entry.
func gitignoreContains(content, entry string) bool {
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimSpace(line) == entry {
			return true
		}
	}
	return false
}

// writeEmbeddedFS walks an fs.FS and writes all files to dstDir.
// Directories are created as needed. Existing files are skipped unless
// force is true. Returns lists of created and skipped relative paths.
func writeEmbeddedFS(fsys fs.FS, dstDir string, force bool) (created, skipped []string, err error) {
	return writeEmbeddedFSSkip(fsys, dstDir, force)
}

// writeEmbeddedFSSkip walks an fs.FS and writes all files to dstDir,
// skipping any paths listed in skipPaths. Directories are created as
// needed. Existing files are skipped unless force is true.
func writeEmbeddedFSSkip(fsys fs.FS, dstDir string, force bool, skipPaths ...string) (created, skipped []string, err error) {
	skipSet := make(map[string]bool, len(skipPaths))
	for _, p := range skipPaths {
		skipSet[p] = true
	}

	err = fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if skipSet[path] {
			return nil
		}

		dstPath := filepath.Join(dstDir, path)

		if d.IsDir() {
			return os.MkdirAll(dstPath, 0o755)
		}

		if !force {
			if _, statErr := os.Stat(dstPath); statErr == nil {
				skipped = append(skipped, path)
				return nil
			}
		}

		if mkErr := os.MkdirAll(filepath.Dir(dstPath), 0o755); mkErr != nil {
			return fmt.Errorf("create parent dir for %s: %w", path, mkErr)
		}

		data, readErr := fs.ReadFile(fsys, path)
		if readErr != nil {
			return fmt.Errorf("read embedded %s: %w", path, readErr)
		}

		if writeErr := os.WriteFile(dstPath, data, 0o644); writeErr != nil {
			return fmt.Errorf("write %s: %w", path, writeErr)
		}
		created = append(created, path)
		return nil
	})
	return created, skipped, err
}
