sonar.sources=cmd,internal,pkg,plugins
sonar.tests=cmd,internal,pkg,plugins
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testutil/**,**/testdata/**,**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
