package instruct

import "strings"

const (
	markerBeginPrefix  = "<!-- BEGIN GENERATED by Crux"
	markerBeginDefault = "<!-- BEGIN GENERATED by Crux -->"
	// MarkerEnd is the static end marker for generated instruction blocks.
	MarkerEnd = "<!-- END GENERATED -->"
)

// InsertGenerated replaces the content between BEGIN/END markers with new
// generated content. If no valid marker pair exists, the entire content is
// wrapped in default markers. User content outside the markers is preserved.
func InsertGenerated(existingContent, generatedContent string) string {
	beginIdx, endIdx := findMarkerPair(existingContent)
	if beginIdx < 0 || endIdx < 0 || beginIdx >= endIdx {
		// No valid pair — wrap in default markers.
		return markerBeginDefault + "\n" + generatedContent + "\n" + MarkerEnd
	}

	var sb strings.Builder

	// Preserve content before the BEGIN marker line.
	before := existingContent[:beginIdx]
	if trimmed := strings.TrimRight(before, " \t"); trimmed != "" {
		sb.WriteString(trimmed)
		sb.WriteByte('\n')
	}

	// Write new markers + generated content.
	sb.WriteString(markerBeginDefault)
	sb.WriteByte('\n')
	sb.WriteString(generatedContent)
	sb.WriteByte('\n')
	sb.WriteString(MarkerEnd)

	// Preserve content after the END marker line.
	afterStart := endIdx + len(MarkerEnd)
	if afterStart < len(existingContent) {
		after := existingContent[afterStart:]
		if trimmed := strings.TrimLeft(after, " \t"); trimmed != "" {
			// Ensure newline separation.
			if !strings.HasPrefix(trimmed, "\n") {
				sb.WriteByte('\n')
			}
			sb.WriteString(trimmed)
		}
	}

	return sb.String()
}

// ExtractUserContent returns user-authored content outside the BEGIN/END
// marker pair. Returns empty strings if no valid marker pair is found.
func ExtractUserContent(existingContent string) (before, after string) {
	beginIdx, endIdx := findMarkerPair(existingContent)
	if beginIdx < 0 || endIdx < 0 || beginIdx >= endIdx {
		return "", ""
	}

	before = strings.TrimSpace(existingContent[:beginIdx])
	afterStart := endIdx + len(MarkerEnd)
	if afterStart < len(existingContent) {
		after = strings.TrimSpace(existingContent[afterStart:])
	}
	return before, after
}

// findMarkerPair locates the BEGIN and END marker positions in content.
// BEGIN is found by scanning lines for the markerBeginPrefix prefix.
// END is found by the last occurrence of MarkerEnd.
// Returns -1 for either index if not found.
func findMarkerPair(content string) (beginIdx, endIdx int) {
	beginIdx = -1
	endIdx = -1

	// Scan lines to find BEGIN marker by prefix.
	lines := strings.SplitAfter(content, "\n")
	offset := 0
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, markerBeginPrefix) {
			beginIdx = offset
			break
		}
		offset += len(line)
	}

	endIdx = strings.LastIndex(content, MarkerEnd)
	return beginIdx, endIdx
}
