package wizard

import (
	"fmt"

	"github.com/roygabriel/crux/internal/config"
	"gopkg.in/yaml.v3"
)

// RenderSummary marshals a Config to YAML with a header comment suitable
// for display in a confirmation step.
func RenderSummary(cfg *config.Config) string {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Sprintf("# Error rendering config: %v", err)
	}
	return "# Generated by crux init\n" + string(data)
}
