package wizard

import (
	"strings"
	"testing"

	"github.com/roygabriel/crux/internal/config"
)

func TestToPluginHuhOptions(t *testing.T) {
	t.Parallel()

	opts := toPluginHuhOptions()
	if got := len(opts); got != len(pluginOptions) {
		t.Fatalf("toPluginHuhOptions() returned %d options, want %d", got, len(pluginOptions))
	}
	for i, opt := range opts {
		if opt.Value != pluginOptions[i].Value {
			t.Errorf("option[%d].Value = %q, want %q", i, opt.Value, pluginOptions[i].Value)
		}
	}
}

func TestToRoleHuhOptions(t *testing.T) {
	t.Parallel()

	opts := toRoleHuhOptions()
	if got := len(opts); got != len(roleOptions) {
		t.Fatalf("toRoleHuhOptions() returned %d options, want %d", got, len(roleOptions))
	}
	for i, opt := range opts {
		if opt.Value != roleOptions[i].Value {
			t.Errorf("option[%d].Value = %q, want %q", i, opt.Value, roleOptions[i].Value)
		}
	}
}

func TestToPermissionHuhOptions(t *testing.T) {
	t.Parallel()

	opts := toPermissionHuhOptions()
	if got := len(opts); got != len(permissionOptions) {
		t.Fatalf("toPermissionHuhOptions() returned %d options, want %d", got, len(permissionOptions))
	}
	for i, opt := range opts {
		if opt.Value != permissionOptions[i].Value {
			t.Errorf("option[%d].Value = %q, want %q", i, opt.Value, permissionOptions[i].Value)
		}
	}
}

func TestRenderSummary(t *testing.T) {
	t.Parallel()

	cfg := config.DefaultConfig()
	cfg.Project.Name = "test-project"
	cfg.Agents = map[string]config.AgentConfig{
		"eng-1": {
			Plugin:     "claude",
			Role:       "engineer",
			Permission: "standard",
		},
	}

	summary := RenderSummary(cfg)

	if !strings.HasPrefix(summary, "# Generated by crux init") {
		t.Error("RenderSummary() missing header comment")
	}

	for _, want := range []string{"test-project", "claude", "engineer", "standard"} {
		if !strings.Contains(summary, want) {
			t.Errorf("RenderSummary() missing expected content %q", want)
		}
	}
}

func TestRenderSummaryEmptyAgents(t *testing.T) {
	t.Parallel()

	cfg := config.DefaultConfig()
	summary := RenderSummary(cfg)

	if !strings.Contains(summary, "project:") {
		t.Error("RenderSummary() missing project section")
	}
}
