package prefs

import (
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ErrFileNotFound indicates the preferences file does not exist.
var ErrFileNotFound = errors.New("preferences file not found")

// yamlHeader is prepended to the preferences file on save.
const yamlHeader = "# Crux Engineering Preferences\n# Generated by crux — edit manually or run: crux prefs edit\n# Schema version: " + CurrentVersion + "\n"

// Store provides YAML persistence for engineering preferences.
type Store struct {
	path   string
	logger *slog.Logger
}

// NewStore creates a Store that reads and writes preferences.yaml inside cruxDir.
// A nil logger falls back to slog.Default().
func NewStore(cruxDir string, logger *slog.Logger) *Store {
	if logger == nil {
		logger = slog.Default()
	}
	return &Store{
		path:   filepath.Join(cruxDir, "preferences.yaml"),
		logger: logger,
	}
}

// Load reads and validates the preferences file.
// Returns ErrFileNotFound if the file does not exist.
func (s *Store) Load() (*Preferences, error) {
	data, err := os.ReadFile(s.path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, ErrFileNotFound
		}
		return nil, fmt.Errorf("reading preferences: %w", err)
	}

	var prefs Preferences
	if err := yaml.Unmarshal(data, &prefs); err != nil {
		return nil, fmt.Errorf("parsing preferences: %w", err)
	}

	if err := prefs.Validate(); err != nil {
		return nil, fmt.Errorf("validating preferences: %w", err)
	}

	return &prefs, nil
}

// Save writes preferences to the YAML file, creating parent directories
// as needed. The version field is set to CurrentVersion before writing.
func (s *Store) Save(prefs *Preferences) error {
	prefs.Version = CurrentVersion

	data, err := yaml.Marshal(prefs)
	if err != nil {
		return fmt.Errorf("marshaling preferences: %w", err)
	}

	dir := filepath.Dir(s.path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating preferences directory: %w", err)
	}

	content := yamlHeader + string(data)
	if err := os.WriteFile(s.path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing preferences: %w", err)
	}

	s.logger.Info("preferences saved", "path", s.path)
	return nil
}

// Exists returns true if the preferences file exists on disk.
func (s *Store) Exists() bool {
	_, err := os.Stat(s.path)
	return err == nil
}
